"""create saved_articles table

Revision ID: c6f99a9c193f
Revises: 99183318112f
Create Date: 2025-04-03 14:19:50.831452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f99a9c193f'
down_revision: Union[str, None] = '99183318112f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('urlToImage', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('published_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_articles_id'), 'saved_articles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_articles_id'), table_name='saved_articles')
    op.drop_table('saved_articles')
    # ### end Alembic commands ###
